# See http://www.appveyor.com/docs/appveyor-yml for many more options

version: 1.0.0.{build}
image: WMF 5
skip_commits:
  message: /updated readme.*|update readme.*s/
build: off

#Kick off the CI/CD pipeline
test_script:
  - ps: . .\build.ps1 -Task Test